NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

skill_read:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Paths\ReadController
