# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.path:
        class: Infrastructure\ODM\Repository\PathsRepository
        arguments: ['@doctrine.odm.mongodb.document_manager']
    app.use_case.get_path:
        class: Domain\UseCase\GetPath
        arguments: ['@app.repository.path']
    app.use_case.add_path:
        class: Domain\UseCase\AddPath
        arguments: ['@app.repository.path']
    app.use_case.add_path_goal:
        class: Domain\UseCase\AddGoal
        arguments: ['@app.repository.path']
    app.use_case.remove_path_goal:
        class: Domain\UseCase\RemoveGoal
        arguments: ['@app.repository.path']
