Domain\Model\Comment:
    type: embeddedDocument
    fields:
        id:
            type: string
            id: true
            strategy: NONE
        author:
            type: string
        text:
            type: string
        timestamp:
            type: date
    embedMany:
        replies:
            targetDocument: Domain\Model\Comment
            strategy: setArray
