Domain\Model\Goal:
    type: embeddedDocument
    fields:
        id:
            type: string
            id: true
            strategy: NONE
        name:
            type: string
        icon:
            type: string
        description:
            type: string
        level:
            type: int
        order:
            type: int
        dueDate:
            type: date
        achieved:
            type: boolean
    embedMany:
        comments:
            targetDocument: Domain\Model\Comment
