Domain\Model\Path:
    fields:
        userId:
            type: string
            id: true
            strategy: NONE
            serialized_name: userId
    embedMany:
        goals:
            targetDocument: Domain\Model\Goal
